/*
 * Bài 8 - Quản lý sinh viên bằng JTable
 */
package javaapplication1;

import java.awt.Font;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 * Form quản lý sinh viên và điểm các môn.
 *
 * Chia làm 2 bảng: bảng trên là danh sách sinh viên, bảng dưới là điểm các môn
 * của sinh viên đang chọn. Mỗi môn nhập 3 đầu điểm chuyên cần / giữa kỳ / cuối
 * kỳ, số môn để tự do nên sinh viên nào học mấy môn cũng nhập được.
 *
 * Dữ liệu lưu ra file sinhvien.txt sau mỗi lần thêm, sửa, xóa nên tắt chương
 * trình mở lại vẫn còn.
 *
 * @author mac
 */
public class Bai08QuanLySinhVien extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai08QuanLySinhVien.class.getName());

    /**
     * Model bảng sinh viên, đồng thời giữ danh sách sinh viên.
     */
    private StudentTableModel studentModel;

    /**
     * Model bảng điểm môn, trỏ vào sinh viên đang chọn ở bảng trên.
     */
    private SubjectTableModel subjectModel;

    /**
     * Bật cờ này lúc đọc file lỗi để không ghi đè file cũ khi chưa hỏi người
     * dùng.
     */
    private boolean choPhepLuu = true;

    /**
     * Creates new form Bai08QuanLySinhVien
     */
    public Bai08QuanLySinhVien() {
        initComponents();

        // In đậm 2 tiêu đề mục cho dễ nhìn
        lblSecSV.setFont(lblSecSV.getFont().deriveFont(Font.BOLD));
        lblSecMon.setFont(lblSecMon.getFont().deriveFont(Font.BOLD));

        // ---- bảng sinh viên ----
        studentModel = new StudentTableModel();
        tblStudents.setModel(studentModel);
        tblStudents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblStudents.setAutoCreateRowSorter(true);
        tblStudents.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                chonSinhVienThayDoi();
            }
        });

        // ---- bảng điểm môn ----
        subjectModel = new SubjectTableModel();
        tblSubjects.setModel(subjectModel);
        tblSubjects.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblSubjects.setAutoCreateRowSorter(true);
        tblSubjects.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                chonMonThayDoi();
            }
        });

        setTitle(getTitle() + " - " + StudentStorage.filePath());
        docFile();
        capNhatTrangThai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSecSV = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        scrollStudents = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        lblSecMon = new javax.swing.JLabel();
        lblSummary = new javax.swing.JLabel();
        lblSubjectName = new javax.swing.JLabel();
        txtSubjectName = new javax.swing.JTextField();
        lblCc = new javax.swing.JLabel();
        txtCc = new javax.swing.JTextField();
        lblGk = new javax.swing.JLabel();
        txtGk = new javax.swing.JTextField();
        lblCk = new javax.swing.JLabel();
        txtCk = new javax.swing.JTextField();
        btnAddSubject = new javax.swing.JButton();
        btnEditSubject = new javax.swing.JButton();
        btnDeleteSubject = new javax.swing.JButton();
        scrollSubjects = new javax.swing.JScrollPane();
        tblSubjects = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bài 8 - Quản lý sinh viên");

        lblSecSV.setText("1. SINH VIÊN");

        lblId.setText("Mã sinh viên:");

        lblName.setText("Họ tên:");

        btnAdd.setText("Thêm SV");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnEdit.setText("Sửa SV");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setText("Xóa SV");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        scrollStudents.setViewportView(tblStudents);

        lblSecMon.setText("2. ĐIỂM CÁC MÔN CỦA SINH VIÊN ĐANG CHỌN");

        lblSummary.setText("Chưa chọn sinh viên nào.");

        lblSubjectName.setText("Tên môn:");

        lblCc.setText("Chuyên cần (10%):");

        lblGk.setText("Giữa kỳ (30%):");

        lblCk.setText("Cuối kỳ (60%):");

        btnAddSubject.setText("Thêm môn");
        btnAddSubject.setEnabled(false);
        btnAddSubject.addActionListener(this::btnAddSubjectActionPerformed);

        btnEditSubject.setText("Sửa môn");
        btnEditSubject.setEnabled(false);
        btnEditSubject.addActionListener(this::btnEditSubjectActionPerformed);

        btnDeleteSubject.setText("Xóa môn");
        btnDeleteSubject.setEnabled(false);
        btnDeleteSubject.addActionListener(this::btnDeleteSubjectActionPerformed);

        scrollSubjects.setViewportView(tblSubjects);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSecSV)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblName))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecMon)
                    .addComponent(lblSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSubjectName)
                        .addGap(12, 12, 12)
                        .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSecSV)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnRefresh))
                .addGap(12, 12, 12)
                .addComponent(scrollStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSecMon)
                .addGap(4, 4, 4)
                .addComponent(lblSummary)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubjectName)
                    .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCc)
                    .addComponent(txtCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGk)
                    .addComponent(txtGk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCk)
                    .addComponent(txtCk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSubject)
                    .addComponent(btnEditSubject)
                    .addComponent(btnDeleteSubject))
                .addGap(12, 12, 12)
                .addComponent(scrollSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ---------- các nút của bảng sinh viên ----------

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String id = docTruongChu(txtId, "Mã sinh viên");
            String name = docTruongChu(txtName, "Họ tên");
            if (studentModel.indexOfId(id, -1) >= 0) {
                throw new IllegalArgumentException("Mã sinh viên \"" + id + "\" đã tồn tại.");
            }

            studentModel.addStudent(new Student(id, name));
            luuFile();

            // Chọn luôn sinh viên vừa thêm rồi nhảy xuống ô Tên môn để nhập điểm ngay
            int modelRow = studentModel.getRowCount() - 1;
            int viewRow = tblStudents.convertRowIndexToView(modelRow);
            tblStudents.setRowSelectionInterval(viewRow, viewRow);
            tblStudents.scrollRectToVisible(tblStudents.getCellRect(viewRow, 0, true));
            txtSubjectName.requestFocusInWindow();
        } catch (IllegalArgumentException ex) {
            baoLoi(ex.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = dongSinhVienDangChon();
        if (row < 0) {
            baoLoi("Hãy chọn một sinh viên trong bảng để sửa.");
            return;
        }
        try {
            String id = docTruongChu(txtId, "Mã sinh viên");
            String name = docTruongChu(txtName, "Họ tên");
            // bỏ qua chính dòng đang sửa khi kiểm tra trùng mã
            if (studentModel.indexOfId(id, row) >= 0) {
                throw new IllegalArgumentException("Mã sinh viên \"" + id + "\" đã tồn tại.");
            }

            studentModel.updateStudent(row, id, name);
            luuFile();
            capNhatTomTat();
        } catch (IllegalArgumentException ex) {
            baoLoi(ex.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = dongSinhVienDangChon();
        if (row < 0) {
            baoLoi("Hãy chọn một sinh viên trong bảng để xóa.");
            return;
        }
        Student s = studentModel.getStudentAt(row);
        int traLoi = JOptionPane.showConfirmDialog(this,
                "Xóa sinh viên \"" + s.getFullName() + "\" cùng " + s.getSubjectCount() + " môn đã nhập?",
                "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (traLoi == JOptionPane.YES_OPTION) {
            studentModel.removeStudent(row);
            luuFile();
            lamMoiForm();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        lamMoiForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    // ---------- các nút của bảng điểm môn ----------

    private void btnAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSubjectActionPerformed
        int studentRow = dongSinhVienDangChon();
        if (studentRow < 0) {
            baoLoi("Hãy chọn một sinh viên trước khi nhập điểm môn.");
            return;
        }
        try {
            Subject m = docFormRaMon();
            Student s = studentModel.getStudentAt(studentRow);
            if (s.indexOfSubjectName(m.getName(), -1) >= 0) {
                throw new IllegalArgumentException("Sinh viên này đã có môn \"" + m.getName() + "\".");
            }

            subjectModel.addSubject(m);
            studentModel.refreshRow(studentRow); // cột Số môn và Điểm TB đổi theo
            luuFile();
            xoaTrangOMon();
            capNhatTomTat();
        } catch (IllegalArgumentException ex) {
            baoLoi(ex.getMessage());
        }
    }//GEN-LAST:event_btnAddSubjectActionPerformed

    private void btnEditSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSubjectActionPerformed
        int studentRow = dongSinhVienDangChon();
        int subjectRow = dongMonDangChon();
        if (studentRow < 0 || subjectRow < 0) {
            baoLoi("Hãy chọn một môn trong bảng dưới để sửa.");
            return;
        }
        try {
            Subject m = docFormRaMon();
            Student s = studentModel.getStudentAt(studentRow);
            // bỏ qua chính môn đang sửa khi kiểm tra trùng tên
            if (s.indexOfSubjectName(m.getName(), subjectRow) >= 0) {
                throw new IllegalArgumentException("Sinh viên này đã có môn \"" + m.getName() + "\".");
            }

            subjectModel.updateSubject(subjectRow, m);
            studentModel.refreshRow(studentRow);
            luuFile();
            capNhatTomTat();
        } catch (IllegalArgumentException ex) {
            baoLoi(ex.getMessage());
        }
    }//GEN-LAST:event_btnEditSubjectActionPerformed

    private void btnDeleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSubjectActionPerformed
        int studentRow = dongSinhVienDangChon();
        int subjectRow = dongMonDangChon();
        if (studentRow < 0 || subjectRow < 0) {
            baoLoi("Hãy chọn một môn trong bảng dưới để xóa.");
            return;
        }
        Subject m = subjectModel.getSubjectAt(subjectRow);
        int traLoi = JOptionPane.showConfirmDialog(this,
                "Xóa môn \"" + m.getName() + "\"?",
                "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (traLoi == JOptionPane.YES_OPTION) {
            subjectModel.removeSubject(subjectRow);
            studentModel.refreshRow(studentRow);
            luuFile();
            xoaTrangOMon();
            capNhatTomTat();
        }
    }//GEN-LAST:event_btnDeleteSubjectActionPerformed

    // ---------- đọc và kiểm tra dữ liệu trên form ----------

    /**
     * Đọc một ô chữ, cắt khoảng trắng hai đầu và kiểm tra rỗng.
     *
     * Chặn luôn dấu | vì file dữ liệu dùng ký tự này để phân cách cột, để lọt
     * vào thì lần sau đọc file lên sẽ sai.
     *
     * @throws IllegalArgumentException khi ô rỗng hoặc có dấu |
     */
    private String docTruongChu(JTextField field, String tenTruong) {
        String value = field.getText().trim();
        if (value.isEmpty()) {
            throw new IllegalArgumentException(tenTruong + " không được để trống.");
        }
        if (value.contains(StudentStorage.SEP)) {
            throw new IllegalArgumentException(tenTruong + " không được chứa ký tự \"" + StudentStorage.SEP + "\".");
        }
        return value;
    }

    /**
     * Đọc một ô điểm: phải là số và nằm trong khoảng 0 - 10.
     *
     * Cho gõ dấu phẩy thay dấu chấm vì bàn phím tiếng Việt hay quen kiểu 8,5.
     *
     * @throws IllegalArgumentException khi không phải số hoặc ngoài khoảng
     */
    private double docDiem(JTextField field, String tenTruong) {
        String text = field.getText().trim().replace(',', '.');
        if (text.isEmpty()) {
            throw new IllegalArgumentException(tenTruong + " không được để trống.");
        }
        double diem;
        try {
            diem = Double.parseDouble(text);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException(tenTruong + " phải là số, ví dụ 8.5");
        }
        if (!QuyChe.diemHopLe(diem)) {
            throw new IllegalArgumentException(tenTruong + " phải nằm trong khoảng "
                    + (int) QuyChe.DIEM_MIN + " đến " + (int) QuyChe.DIEM_MAX + ".");
        }
        return diem;
    }

    /**
     * Đọc 4 ô của phần môn học rồi trả về một Subject.
     *
     * @throws IllegalArgumentException khi dữ liệu chưa hợp lệ
     */
    private Subject docFormRaMon() {
        String name = docTruongChu(txtSubjectName, "Tên môn");
        double cc = docDiem(txtCc, "Điểm chuyên cần");
        double gk = docDiem(txtGk, "Điểm giữa kỳ");
        double ck = docDiem(txtCk, "Điểm cuối kỳ");
        return new Subject(name, cc, gk, ck);
    }

    // ---------- đổi dòng trên bảng sang dòng trong model ----------

    /**
     * Đổi dòng đang chọn ở bảng sinh viên sang chỉ số dòng trong model.
     *
     * Phải đổi vì bảng có sắp xếp: dòng thứ 0 trên bảng chưa chắc là phần tử thứ
     * 0 trong danh sách.
     *
     * @return chỉ số dòng trong model, hoặc -1 nếu chưa chọn dòng nào
     */
    private int dongSinhVienDangChon() {
        int viewRow = tblStudents.getSelectedRow();
        if (viewRow < 0) {
            return -1;
        }
        return tblStudents.convertRowIndexToModel(viewRow);
    }

    /**
     * Đổi dòng đang chọn ở bảng điểm môn sang chỉ số dòng trong model.
     *
     * @return chỉ số dòng trong model, hoặc -1 nếu chưa chọn dòng nào
     */
    private int dongMonDangChon() {
        int viewRow = tblSubjects.getSelectedRow();
        if (viewRow < 0) {
            return -1;
        }
        return tblSubjects.convertRowIndexToModel(viewRow);
    }

    // ---------- phản ứng khi chọn dòng ----------

    /**
     * Chọn sinh viên nào thì đổ mã và họ tên lên form, đồng thời đổi luôn nội
     * dung bảng điểm môn sang sinh viên đó.
     */
    private void chonSinhVienThayDoi() {
        int row = dongSinhVienDangChon();
        if (row >= 0) {
            Student s = studentModel.getStudentAt(row);
            txtId.setText(s.getId());
            txtName.setText(s.getFullName());
            subjectModel.setStudent(s);
        } else {
            subjectModel.setStudent(null);
        }
        xoaTrangOMon();
        capNhatTrangThai();
    }

    /**
     * Chọn môn nào thì đổ 4 ô của môn đó lên form để sửa.
     */
    private void chonMonThayDoi() {
        int row = dongMonDangChon();
        if (row >= 0) {
            Subject m = subjectModel.getSubjectAt(row);
            txtSubjectName.setText(m.getName());
            txtCc.setText(hienSo(m.getChuyenCan()));
            txtGk.setText(hienSo(m.getGiuaKy()));
            txtCk.setText(hienSo(m.getCuoiKy()));
        }
        capNhatTrangThai();
    }

    // ---------- cập nhật trạng thái giao diện ----------

    /**
     * Bật tắt các nút theo tình trạng đang chọn dòng nào.
     *
     * Chưa chọn sinh viên thì không sửa xóa sinh viên được, cũng không nhập điểm
     * môn được vì chưa biết nhập cho ai. Chưa chọn môn thì không sửa xóa môn
     * được.
     */
    private void capNhatTrangThai() {
        boolean coSinhVien = dongSinhVienDangChon() >= 0;
        boolean coMon = coSinhVien && dongMonDangChon() >= 0;

        btnEdit.setEnabled(coSinhVien);
        btnDelete.setEnabled(coSinhVien);

        txtSubjectName.setEnabled(coSinhVien);
        txtCc.setEnabled(coSinhVien);
        txtGk.setEnabled(coSinhVien);
        txtCk.setEnabled(coSinhVien);

        btnAddSubject.setEnabled(coSinhVien);
        btnEditSubject.setEnabled(coMon);
        btnDeleteSubject.setEnabled(coMon);

        capNhatTomTat();
    }

    /**
     * Viết lại dòng tóm tắt phía trên bảng điểm môn.
     */
    private void capNhatTomTat() {
        int row = dongSinhVienDangChon();
        if (row < 0) {
            lblSummary.setText("Chưa chọn sinh viên nào. Chọn một dòng ở bảng trên để nhập điểm môn.");
            return;
        }
        Student s = studentModel.getStudentAt(row);
        if (s.getSubjectCount() == 0) {
            lblSummary.setText(s.getId() + " - " + s.getFullName() + "  |  chưa nhập môn nào");
            return;
        }
        lblSummary.setText(s.getId() + " - " + s.getFullName()
                + "  |  Số môn: " + s.getSubjectCount()
                + "  |  Điểm TB: " + QuyChe.lamTron2(s.getDiemTB())
                + "  |  Xếp loại: " + s.getRanking());
    }

    /**
     * Xóa trắng cả form và bỏ chọn dòng ở hai bảng.
     */
    private void lamMoiForm() {
        tblStudents.clearSelection();
        tblSubjects.clearSelection();
        txtId.setText("");
        txtName.setText("");
        xoaTrangOMon();
        capNhatTrangThai();
        txtId.requestFocusInWindow();
    }

    /**
     * Xóa trắng 4 ô của phần môn học và bỏ chọn dòng ở bảng điểm môn.
     */
    private void xoaTrangOMon() {
        tblSubjects.clearSelection();
        txtSubjectName.setText("");
        txtCc.setText("");
        txtGk.setText("");
        txtCk.setText("");
    }

    // ---------- đọc ghi file ----------

    /**
     * Đọc dữ liệu từ file lúc mở chương trình.
     *
     * File lỗi thì báo cho người dùng biết và mở với danh sách rỗng, nhưng khóa
     * việc ghi file lại để không làm mất dữ liệu cũ khi chưa được đồng ý.
     */
    private void docFile() {
        try {
            List<Student> students = StudentStorage.load();
            studentModel.setData(students);
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.WARNING, "Không đọc được file dữ liệu", ex);
            choPhepLuu = false;
            JOptionPane.showMessageDialog(this,
                    ex.getMessage()
                    + "\n\nChương trình mở với danh sách rỗng."
                    + "\nLần đầu bạn thêm, sửa hay xóa sẽ được hỏi trước khi ghi đè file cũ.",
                    "Không đọc được dữ liệu", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Ghi cả danh sách ra file sau mỗi lần thêm, sửa, xóa.
     */
    private void luuFile() {
        if (!choPhepLuu) {
            int traLoi = JOptionPane.showConfirmDialog(this,
                    "File " + StudentStorage.FILE_NAME + " cũ đang lỗi, ghi tiếp là mất nội dung cũ."
                    + "\nVẫn ghi đè?",
                    "Xác nhận ghi đè", JOptionPane.YES_NO_OPTION);
            if (traLoi != JOptionPane.YES_OPTION) {
                return;
            }
            choPhepLuu = true; // đã đồng ý một lần thì các lần sau ghi luôn
        }
        try {
            StudentStorage.save(studentModel.getData());
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Không ghi được file dữ liệu", ex);
            JOptionPane.showMessageDialog(this,
                    "Không ghi được file " + StudentStorage.filePath() + "\n" + ex.getMessage()
                    + "\n\nDữ liệu vẫn còn trên bảng nhưng chưa được lưu.",
                    "Lỗi ghi file", JOptionPane.ERROR_MESSAGE);
        }
    }

    // ---------- tiện ích nhỏ ----------

    /**
     * Hiện số cho gọn: 9 thay vì 9.0, còn số lẻ thì giữ 2 chữ số thập phân.
     */
    private static String hienSo(double value) {
        double v = QuyChe.lamTron2(value);
        if (v == Math.rint(v)) {
            return String.valueOf((long) v);
        }
        return String.valueOf(v);
    }

    private void baoLoi(String message) {
        JOptionPane.showMessageDialog(this, message, "Dữ liệu chưa hợp lệ", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bai08QuanLySinhVien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddSubject;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteSubject;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditSubject;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel lblCc;
    private javax.swing.JLabel lblCk;
    private javax.swing.JLabel lblGk;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSecMon;
    private javax.swing.JLabel lblSecSV;
    private javax.swing.JLabel lblSubjectName;
    private javax.swing.JLabel lblSummary;
    private javax.swing.JScrollPane scrollStudents;
    private javax.swing.JScrollPane scrollSubjects;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTable tblSubjects;
    private javax.swing.JTextField txtCc;
    private javax.swing.JTextField txtCk;
    private javax.swing.JTextField txtGk;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSubjectName;
    // End of variables declaration//GEN-END:variables
}
